program = {stmt};

stmt = vardcl
      | assgn;

moddecl = "Mod", id, eos;

vardcl = id, tspec, id, eos;

assgn = id, assgnOp, expr, eos;

expr = id 
      | num
      | "(", expr, ")"
      | unaOp, expr
      | expr, binOp, expr;

unaOp = "-";
binOp = "+" | "-" | "*" | "/";

eos = ";";

tspec = ":";

assgnOp = "=";

id = unicodeChar, {(digit | unicodeChar | "_")};

unicodeChar = ? unicode character ?;

num = integer | decimal;

integer = (["-"], digitNoNull, {digit}) | "0";

decimal = (["-"], {digit}, ".", digit, {digit}) | {digit};

digit = "0" | "1" | "2" | "3" | "4" 
            | "5" | "6" | "7" | "8" | "9";

digitNoNull = "1" | "2" | "3" | "4" 
                  | "5" | "6" | "7" | "8" | "9";
